{"SketchupExtension.new":28,"Sketchup.register_extension":29,"File.join":154,"Sketchup":11,"Sketchup.version":14,"Sketchup.find_support_file":7,"FileTest.exist?":9,"UI.messagebox":45,"UI.openURL":13,"File.dirname":18,"Method":3,"Encoding":6,"Sketchup.require":7,"TOPLEVEL_BINDING":1,"Time.now":29,"Module":8,"File.basename":30,"MB_YESNO":10,"IDYES":5,"Sketchup.platform":6,"UI::HtmlDialog":4,"UI::HtmlDialog.new":2,"Sketchup.active_model":72,"Sketchup::Model#active_view":14,"Sketchup::View#vpheight":4,"UI::HtmlDialog::STYLE_UTILITY":2,"Sketchup.get_locale":4,"UI.openpanel":1,"Enumerable.entries":5,"File.delete":6,"File.exists?":4,"UI.start_timer":6,"UI.stop_timer":3,"File.open":14,"File.read":3,"Sketchup::Texture#write":14,"IO.binread":1,"IO.read":1,"UI::HtmlDialog#set_on_closed":1,"RUBY_PLATFORM":7,"UI::Toolbar":3,"UI::Toolbar.new":3,"UI.menu":6,"UI::Command":18,"UI::Command.new":18,"ENV":16,"UI::Command#tooltip":40,"UI::Command#status_bar_text":5,"UI::Command#large_icon":18,"UI::Command#small_icon":18,"UI::Toolbar#add_item":40,"UI::Toolbar#get_last_state":2,"UI::Toolbar#restore":1,"LanguageHandler.new":4,"STDERR":1,"SystemExit":1,"ARGV":1,"Sketchup.extensions":4,"Gem":1,"Gem.find_files":1,"Sketchup::AttributeDictionaries#delete":12,"Interrupt":1,"Integer":176,"Test":5,"Regexp.new":2,"Signal.list":1,"NotImplementedError":17,"Sketchup::Selection#first":33,"Marshal.dump":1,"Sketchup::Http::Request#method":1,"UI::Notification#message":10,"IO":2,"Sketchup::Model#options":1,"Enumerable.all?":23,"Encoding::ASCII_8BIT":1,"Exception":52,"RUBY_ENGINE":4,"RUBY_DESCRIPTION":1,"Process::CLOCK_MONOTONIC":2,"Process.clock_gettime":1,"Sketchup.write_default":15,"Sketchup::Model#active_entities":23,"Sketchup::Model#selection":40,"Sketchup::Entity#typename":2,"Sketchup::Edge#end":20,"Sketchup::Vertex#position":125,"Sketchup::Model#start_operation":17,"Sketchup::Edge#explode_curve":3,"Sketchup::Entities#add_group":12,"Sketchup::Entities#add_curve":3,"Sketchup::Model#commit_operation":26,"Sketchup.is_pro?":5,"Sketchup::SandboxTools":2,"Layout":1,"LoadError":5,"UI::WebDialog":21,"UI::WebDialog.new":6,"TB_VISIBLE":1,"Sketchup::Model#select_tool":12,"Array":163,"GL_LINES":38,"Sketchup::View#invalidate":76,"Sketchup::Face":42,"Geom::Point3d#transform":16,"Geom::PolygonMesh#count_polygons":6,"Sketchup::Edge":58,"UI.beep":5,"Geom.fit_plane_to_points":4,"Z_AXIS":35,"Geom::Point3d#vector_to":11,"Sketchup::Entities#transform_by_vectors":5,"Sketchup::View#draw":55,"GL_LINE_LOOP":9,"GL_TRIANGLES":12,"Sketchup::Selection#shift":14,"Sketchup::Edge#soft?":5,"Geom::PolygonMesh":1,"Geom::PolygonMesh.new":1,"Sketchup::Face#mesh":6,"Geom::PolygonMesh#add_polygon":1,"Sketchup::PickHelper":4,"Sketchup::Entity":13,"Geom::Transformation":45,"Geom::Transformation.new":24,"Hash":66,"MK_LBUTTON":6,"Geom.closest_points":3,"Sketchup::View#pixels_to_model":20,"Geom::BoundingBox":16,"Geom::BoundingBox.new":8,"Geom::BoundingBox#min":12,"Geom::Point3d#z":18,"Geom::BoundingBox#max":12,"Geom::Vector3d#reverse":22,"Geom::Point3d#transform!":6,"Geom::Point3d#to_a":2,"Geom::Point3d#offset!":3,"UI.set_cursor":3,"Sketchup::View#draw_points":18,"Sketchup::AttributeDictionary#values":2,"Sketchup::View#draw2d":19,"Sketchup::View#screen_coords":14,"Geom::Point3d#offset":25,"Geom::PolygonMesh#point_index":1,"Sketchup::Face#plane":8,"Geom::Transformation#inverse":9,"Sketchup::Entities#add_line":10,"Sketchup::Vertex":10,"Geom::Point3d":199,"Sketchup::Model#edit_transform":3,"UI":20,"Sketchup::Entities#add_cpoint":5,"Sketchup::Entities#add_cline":5,"ORIGIN":14,"Sketchup::Face#normal":23,"Geom::Vector3d#samedirection?":12,"Sketchup::Face#pushpull":3,"Sketchup::InputPoint":6,"Sketchup::InputPoint.new":6,"Geom.linear_combination":24,"Sketchup::Selection#clear":8,"Sketchup::Selection#add":8,"GL_LINE_STRIP":12,"String":190,"Geom::Point3d.new":95,"Length":24,"Sketchup::View":51,"Sketchup::Edge#other_vertex":4,"Sketchup::Entities":19,"Sketchup::Vertex#edges":4,"Process":8,"Time":5,"Sketchup::Drawingelement#layer":7,"Sketchup::Entities#intersect_with":2,"Sketchup::Edge#find_faces":1,"Sketchup::Drawingelement#erase!":9,"Sketchup::Face#outer_loop":8,"Sketchup::Entities#add_face":4,"ArgumentError":49,"Sketchup::Loop#outer?":3,"Sketchup::Group":15,"Sketchup::Group.method_defined?":2,"Sketchup::Entities#erase_entities":10,"GL_QUADS":8,"Y_AXIS":2,"X_AXIS":7,"Sketchup::Selection#each":1,"Sketchup.set_status_text":4,"Sketchup::ComponentInstance":7,"Geom::Point3d#clone":1,"Sketchup::ConstructionPoint":2,"Sketchup::Selection":2,"Geom::Vector3d#parallel?":6,"Geom::Point3d#project_to_plane":3,"Sketchup::Face#classify_point":5,"Dir.glob":18,"Sketchup::Set":2,"Sketchup::Selection#empty?":3,"MB_MULTILINE":4,"GC":5,"Sketchup::Model#materials":23,"Sketchup::Materials#current":4,"Sketchup::Model#definitions":21,"Sketchup::DefinitionList#length":4,"Sketchup::DefinitionList#purge_unused":2,"Sketchup::Model#number_faces":4,"Sketchup::Layers#length":2,"Sketchup::Materials#length":2,"Sketchup::Materials#purge_unused":2,"Sketchup::Model#styles":3,"Sketchup::Styles#count":2,"Sketchup::Styles#purge_unused":1,"UI.refresh_inspectors":1,"Sketchup.send_action":1,"Sketchup::Layer#visible?":5,"Geom::Vector3d#angle_between":8,"Sketchup::ComponentDefinition":9,"Sketchup::Behavior#cuts_opening?":2,"Geom::Point3d#on_plane?":3,"Sketchup.create_texture_writer":4,"Sketchup::Face#get_UVHelper":4,"Sketchup::Material#color":6,"Sketchup::Material#alpha":9,"Sketchup::Material#materialType":4,"Sketchup::Texture#image_width":1,"Sketchup::Texture#image_height":2,"Sketchup::Material#display_name":15,"Sketchup::Materials#remove":2,"Sketchup::Materials#count":1,"Sketchup::Materials#add":1,"File.exist?":19,"Sketchup::Texture#filename":10,"Sketchup::Texture#width":7,"Sketchup::Texture#height":7,"Sketchup::DefinitionList#unique_name":2,"Sketchup::Model":18,"Object::RUBY_PLATFORM":2,"SketchupExtension":4,"Symbol":37,"TypeError":5,"RUBY_VERSION":5,"RUBY_PATCHLEVEL":3,"RuntimeError":4,"UI::WebDialog#min_width":5,"UI::WebDialog#max_width":2,"UI::WebDialog#min_height":5,"UI::WebDialog#max_height":2,"UI::WebDialog#get_element_value":4,"Sketchup.respond_to?":5,"Sketchup.is_64bit?":2,"Sketchup.app_name":1,"Sketchup::Model#get_product_family":2,"Sketchup::Console#show":3,"SKETCHUP_CONSOLE":1,"Sketchup::Curve":2,"Sketchup::Curve#is_polygon?":1,"Sketchup::ArcCurve":1,"Sketchup::AttributeDictionaries":2,"Sketchup::AttributeDictionary":2,"File.expand_path":10,"Sketchup::Text#point":1,"Sketchup::Color":30,"Kernel.clone":1,"Sketchup::Color.new":16,"MB_OKCANCEL":2,"IO.readlines":1,"MB_OK":1,"IDOK":1,"Sketchup::Menu":1,"Numeric":60,"Object":8,"UI.create_cursor":3,"Geom::Vector3d":45,"Geom::Transformation.rotation":10,"Geom::Vector3d#transform":1,"File.directory?":8,"IOError":3,"Errno::EACCES":1,"Gem::Resolver::Molinillo::UI.debug":1,"Kernel":1,"Class":11,"Proc":8,"Float":21,"Sketchup::ComponentDefinition#image?":10,"Sketchup::Entities#transform_entities":2,"Sketchup::ComponentDefinition#instances":7,"Geom::Point3d.linear_combination":6,"Enumerable":14,"Array.new":3,"NoMethodError":2,"Sketchup::Vertex#used_by?":1,"Sketchup::TextureWriter":1,"Geom::Vector3d#axes":9,"Geom::Vector3d.new":4,"Geom::Transformation.axes":4,"Math.cos":3,"Math.sin":3,"Math::PI":6,"Math.sqrt":2,"Geom::Transformation#origin":15,"Sketchup::Http::Request#cancel":4,"Sketchup::View#camera":7,"Sketchup::Camera#perspective?":2,"Geom::Vector3d#perpendicular?":2,"Sketchup::View#inputpoint":1,"Geom::Point3d#project_to_line":4,"Sketchup.format_angle":1,"GL_POLYGON":7,"Geom::Transformation.scaling":3,"CONSTRAIN_MODIFIER_MASK":6,"Data":1,"StandardError":6,"GL_TRIANGLE_FAN":1,"GL_POINTS":3,"IndexError":1,"Sketchup::Image":6,"Sketchup::Material":5,"Sketchup::DefinitionList#each":4,"Geom::Vector3d#inspect":1,"Hash.new":2,"Sketchup::RegionalSettings.decimal_separator":5,"TrueClass":1,"FalseClass":1,"Sketchup::RegionalSettings.list_separator":1,"Dir.mkdir":4,"Sketchup::Model#abort_operation":3,"Sketchup::View#vpwidth":3,"Sketchup::Model#tools":2,"Sketchup::ComponentDefinition#count_instances":4,"Comparable.between?":1,"Geom::PolygonMesh#points":2,"Time.new":2,"Range":2,"SyntaxError":1,"Sketchup::View#refresh":1,"Dir.pwd":1,"Dir.chdir":1,"File.mtime":2,"SystemCallError":6,"File.chmod":6,"Dir.rmdir":2,"Errno::EEXIST":3,"Errno::ENOTDIR":3,"File.link":1,"File.unlink":4,"File.file?":1,"Sketchup::Group#copy":1,"File.rename":1,"Errno::EXDEV":1,"File.lstat":2,"File.stat":7,"Process.euid":1,"File.utime":3,"Geom::Vector3d#%":1,"Errno::ENOENT":3,"File.chown":2,"Kernel.respond_to?":6,"Errno::EPERM":1,"Sketchup::Styles#add_style":1,"Comparable":1,"ObjectSpace.define_finalizer":1,"ObjectSpace.undefine_finalizer":1,"Process.pid":1,"File":4,"FALSE":3,"TRUE":2,"Queue":1,"Geom::Point3d#distance":4,"Sketchup::View#lock_inference":6,"CONSTRAIN_MODIFIER_KEY":2,"Sketchup::View#inference_locked?":4,"VK_CONTROL":2,"Sketchup::View#set_color_from_line":3,"Sketchup::View#draw_text":2,"IO::SEEK_SET":2,"Struct":2,"Sketchup.debug_mode?":8,"Sketchup::Menu#add_submenu":1,"UI.toolbar":1,"Sketchup::Entity#entityID":2,"Sketchup::Face#set_texture_projection":1,"Sketchup::Face#get_texture_projection":1,"Sketchup::Text#text":2,"Geom.point_in_polygon_2D":1,"Geom::PolygonMesh#polygons":1,"IO::SEEK_CUR":1,"VK_UP":1,"VK_RIGHT":1,"VK_DOWN":1,"VK_LEFT":1,"UI::Toolbar#show":1,"MF_CHECKED":4,"MF_UNCHECKED":4,"MF_ENABLED":1,"MF_GRAYED":1,"UI::WebDialog#set_on_close":1,"Sketchup::View#zoom":1,"Geom::Point3d#x":4,"Geom::Point3d#y":4,"Sketchup::Edge#reversed_in?":1,"Geom::Vector3d#z":1}